// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWF.CA.Data;

namespace SWF.CA.Data.Migrations
{
    [DbContext(typeof(CaContext))]
    [Migration("20190327183414_initia")]
    partial class initia
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SWF.CA.Data.Models.InsuranceOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MaxSquareMeter");

                    b.Property<int>("MinSquareMeter");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("InsuranceOptions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c91dd9e9-7af5-4aa8-87ea-dca5d869af3b"),
                            MaxSquareMeter = 50,
                            MinSquareMeter = 0,
                            Name = "LowCostOption"
                        },
                        new
                        {
                            Id = new Guid("9b9fe51d-8c9f-4b0f-b2ca-b1293aea5c67"),
                            MaxSquareMeter = 100,
                            MinSquareMeter = 51,
                            Name = "MediumCostOption"
                        },
                        new
                        {
                            Id = new Guid("5e65ea0b-e2d6-423d-ae72-fd1b74bd4430"),
                            MaxSquareMeter = 10000,
                            MinSquareMeter = 101,
                            Name = "HighCostOption"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
